export const EXEPENSE_LIST = [
  {
    accountNumber: 1,
    firstName: 'admin',
    lastName: 'admin',
    email: 'admin@email.com',
    password: 'admin',
    balance: 0,
    role: 'admin',
  },
  {
    accountNumber: 1560222970000,
    firstName: 'John',
    lastName: 'Doe',
    email: 'jd@email.com',
    password: 'jd',
    balance: 20000.0,
    role: 'user',
  },
  {
    accountNumber: 1560222970001,
    firstName: 'John',
    lastName: 'Smith',
    email: 'js@email.com',
    password: 'js',
    balance: 30000.0,
    role: 'user',
  },
  {
    accountNumber: 1560222970002,
    firstName: 'Maria',
    lastName: 'Dela Cruz',
    email: 'mdc@email.com',
    password: 'mdc',
    balance: 40000.0,
    role: 'user',
  },
  {
    accountNumber: 1560222970003,
    firstName: 'Juan',
    lastName: 'Dela Cruz',
    email: 'jdc@email.com',
    password: 'jdc',
    balance: 0.0,
    role: 'user',
  },
];
